'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bridgenote
    Public Property id As Integer
    Public Property recorddate As Date
    Public Property recordprogram As String
    Public Property recorduserid As String
    Public Property recordvalid As Boolean
    Public Property repair As String
    Public Property nextinspection As Nullable(Of Integer)
    Public Property inspectionway As String
    Public Property memo As String

End Class
