'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bridgehistory
    Public Property id As Integer
    Public Property recorddate As Date
    Public Property recordprogram As String
    Public Property recorduserid As String
    Public Property recordvalid As Boolean
    Public Property bridgename As String
    Public Property route As String
    Public Property address As String
    Public Property latitude As String
    Public Property longitude As String
    Public Property made As Nullable(Of Integer)
    Public Property bridgelength As Nullable(Of Decimal)
    Public Property bridgewidth As Nullable(Of Decimal)
    Public Property span As Nullable(Of Integer)
    Public Property bridgestructure As String
    Public Property uppermaterial As String
    Public Property lowermaterial As String
    Public Property undercondition As String
    Public Property emergencyroad As String

End Class
