'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bridgemanagementview
    Public Property id As Integer
    Public Property bridgename As String
    Public Property bridgenameruby As String
    Public Property route As String
    Public Property address As String
    Public Property latitude As String
    Public Property longitude As String
    Public Property made As Nullable(Of Integer)
    Public Property bridgeage As Nullable(Of Integer)
    Public Property bridgelength As Nullable(Of Decimal)
    Public Property bridgewidth As Nullable(Of Decimal)
    Public Property span As Nullable(Of Integer)
    Public Property bridgestructure As String
    Public Property uppermaterial As String
    Public Property lowermaterial As String
    Public Property undercondition As String
    Public Property emergencyroad As String
    Public Property repair As String
    Public Property nextinspection As Nullable(Of Integer)
    Public Property inspectionway As String
    Public Property memo As String
    Public Property inspectionyear As Nullable(Of Integer)
    Public Property inspectioner As String
    Public Property inspectionundercondition As String
    Public Property alternatepath As String
    Public Property generalroad As String
    Public Property inspectionemergencyroad As String
    Public Property occupancy As String
    Public Property soundness As String
    Public Property uppermaterialmain As String
    Public Property uppermaterialside As String
    Public Property uppermaterialfloor As String
    Public Property undermaterial As String
    Public Property bearing As String
    Public Property face As String
    Public Property datasavedir As String

End Class
