'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class bridgemanagementEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=bridgemanagementEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property bridge() As DbSet(Of bridge)
    Public Overridable Property bridgehistory() As DbSet(Of bridgehistory)
    Public Overridable Property bridgenote() As DbSet(Of bridgenote)
    Public Overridable Property bridgenotehistory() As DbSet(Of bridgenotehistory)
    Public Overridable Property inspection() As DbSet(Of inspection)
    Public Overridable Property inspectionhistory() As DbSet(Of inspectionhistory)
    Public Overridable Property inspectionexcel() As DbSet(Of inspectionexcel)

End Class
