'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inspectionhistory
    Public Property id As Integer
    Public Property recorddate As Date
    Public Property recordprogram As String
    Public Property recorduserid As String
    Public Property recordvalid As Boolean
    Public Property inspectionyear As Nullable(Of Integer)
    Public Property inspectioner As String
    Public Property undercondition As String
    Public Property alternatepath As String
    Public Property generalroad As String
    Public Property emergencyroad As String
    Public Property occupancy As String
    Public Property soundness As String
    Public Property uppermaterialmain As String
    Public Property uppermaterialside As String
    Public Property uppermaterialfloor As String
    Public Property undermaterial As String
    Public Property bearing As String
    Public Property face As String
    Public Property datasavedir As String

End Class
