'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inspectionexcel
    Public Property ident As Integer
    Public Property datadir As String
    Public Property id As Nullable(Of Integer)
    Public Property inspectionyear As Nullable(Of Integer)
    Public Property inspectioner As String
    Public Property undercondition As String
    Public Property alternatepath As String
    Public Property generalroad As String
    Public Property emergencyroad As String
    Public Property occupancy As String
    Public Property soundness As String
    Public Property uppermaterial As String
    Public Property undermaterial As String
    Public Property bearing As String
    Public Property face As String
    Public Property [error] As Boolean
    Public Property message As String

End Class
